version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"

    groups:
      dev-tools:
        patterns:
          - "pytest*"
          - "mypy*"
          - "ruff*"
          # Optionally add if you use typing stubs:
          # - "types-*"
      gradio-majors:
        patterns:
          - "gradio"
        update-types:
          - "major"
    # Policy: Track all Gradio updates (including majors) to stay consistent with upstream.

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
